name: srv_demo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  connectivity_plus: ^5.0.2
  dartz: ^0.10.1
  email_validator: ^2.0.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.0.0
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  get_it: ^7.6.6
  go_router: ^6.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.8
  build_test: ^2.2.2
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  lint: ^2.0.0
  

flutter:
  uses-material-design: true

  assets:
    - resources/images/
